/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Gallery = {
  _id: string;
  _type: "gallery";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    caption?: string;
    _type: "image";
    _key: string;
  }>;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type InstructorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "instructor";
};

export type Event = {
  _id: string;
  _type: "event";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  startDateTime: string;
  endDateTime?: string;
  location?: string;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  instructors?: Array<
    {
      _key: string;
    } & InstructorReference
  >;
};

export type Instructor = {
  _id: string;
  _type: "instructor";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  instruments?: Array<string>;
  bio?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  email?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Gallery
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | InstructorReference
  | Event
  | Instructor
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../web/src/pages/events/[slug].astro
// Variable: EVENT_SLUGS_QUERY
// Query: *[_type == "event" && defined(slug.current)]{ "params": { "slug": slug.current } }
export type EVENT_SLUGS_QUERY_RESULT = Array<{
  params: {
    slug: string;
  };
}>;

// Source: ../web/src/pages/events/[slug].astro
// Variable: EVENT_QUERY
// Query: *[_type == "event" && slug.current == $slug][0]{		title, startDateTime, endDateTime, location, coverImage, description,		instructors[]->{ _id, name }	}
export type EVENT_QUERY_RESULT = {
  title: string;
  startDateTime: string;
  endDateTime: string | null;
  location: string | null;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  description: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  instructors: Array<{
    _id: string;
    name: string;
  }> | null;
} | null;

// Source: ../web/src/pages/events/index.astro
// Variable: EVENTS_QUERY
// Query: *[_type == "event" && defined(slug.current)] | order(startDateTime asc){ _id, title, slug, startDateTime, location }
export type EVENTS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: Slug;
  startDateTime: string;
  location: string | null;
}>;

// Source: ../web/src/pages/galleries/[slug].astro
// Variable: GALLERY_SLUGS_QUERY
// Query: *[_type == "gallery" && defined(slug.current)]{ "params": { "slug": slug.current } }
export type GALLERY_SLUGS_QUERY_RESULT = Array<{
  params: {
    slug: string;
  };
}>;

// Source: ../web/src/pages/galleries/[slug].astro
// Variable: GALLERY_QUERY
// Query: *[_type == "gallery" && slug.current == $slug][0]{ title, images }
export type GALLERY_QUERY_RESULT = {
  title: string;
  images: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    caption?: string;
    _type: "image";
    _key: string;
  }> | null;
} | null;

// Source: ../web/src/pages/galleries/index.astro
// Variable: GALLERIES_QUERY
// Query: *[_type == "gallery" && defined(slug.current)] | order(title asc){ _id, title, slug, "cover": images[0] }
export type GALLERIES_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: Slug;
  cover: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    caption?: string;
    _type: "image";
    _key: string;
  } | null;
}>;

// Source: ../web/src/pages/instructors/index.astro
// Variable: INSTRUCTORS_QUERY
// Query: *[_type == "instructor"] | order(name asc){ _id, name, photo, instruments, bio, email }
export type INSTRUCTORS_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  photo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  instruments: Array<string> | null;
  bio: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  email: string | null;
}>;

// Query TypeMap
declare global {
  interface SanityQueries {
    '*[_type == "event" && defined(slug.current)]{ "params": { "slug": slug.current } }': EVENT_SLUGS_QUERY_RESULT;
    '*[_type == "event" && slug.current == $slug][0]{\n\t\ttitle, startDateTime, endDateTime, location, coverImage, description,\n\t\tinstructors[]->{ _id, name }\n\t}': EVENT_QUERY_RESULT;
    '*[_type == "event" && defined(slug.current)] | order(startDateTime asc){ _id, title, slug, startDateTime, location }': EVENTS_QUERY_RESULT;
    '*[_type == "gallery" && defined(slug.current)]{ "params": { "slug": slug.current } }': GALLERY_SLUGS_QUERY_RESULT;
    '*[_type == "gallery" && slug.current == $slug][0]{ title, images }': GALLERY_QUERY_RESULT;
    '*[_type == "gallery" && defined(slug.current)] | order(title asc){ _id, title, slug, "cover": images[0] }': GALLERIES_QUERY_RESULT;
    '*[_type == "instructor"] | order(name asc){ _id, name, photo, instruments, bio, email }': INSTRUCTORS_QUERY_RESULT;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
